config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord 
    belongs_to :post

end

app/models/post.rb
class Post < ApplicationRecord  
    validates :title, :description, :marktsegment, presence: true
has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.new(comment_params)

        if @comment.save
            flash.notice = "Comment saved"
            redirect_to post_path(@post)
        else
            flash.alert = "comment not saved"
            redirect_to post_path(@post)
        end
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
    
        if @comment.destroy
            flash.notice = "Comment deleted"
            redirect_to post_path(@post)
        else
            flash.alert = "Could not delete Comment"
            redirect_to post_path(@post)
        end
    end
    private

    def comment_params 
        params.require(:comment).permit(
            :text,
            :name,
            :email
        )
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)

        if @post.save
            flash.notice= 'all good'
            redirect_to '/posts'
        else
            flash.alert= 'something went wrong'
            render :new
        end
    end

    def post_params
        params.require(:post).permit(
        :title,
        :help,
        :description,
        :marktsegment,
        :keywords
        )
    end
    
    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
            flash.notice = "post updated"
            redirect_to  posts_path
        else
            flash.alert = 'Could not update post'
            render :edit
        end
    end

    def destroy
        @post = Post.find(params[:id])
        if @post.destroy
            flash.notice = "post deleted"
            redirect_to posts_path
        else 
            flash.alert = "Could not delete Post"
            ridirect_to posts_path
        end
    end
    
    def show
        @post = Post.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pitchweb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="bg-dark text-white">


  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li>
              <img src="https://upload.wikimedia.org/wikipedia/commons/9/9a/Universit%C3%A4t_Witten-Herdecke.svg" alt="" width="100" height="40" class="d-inline-block align-text-top me-3">
            </li>
            <li class="nav-item">
              <%= link_to 'Alle Pitches', posts_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Neuer Pitch', new_post_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
      </div>
</nav>

  
  <% flash.each do |type, msg| %>
    <div class="alert alert-info">
      <%= msg %>
    </div>
  <% end %>


  <div class="container mt-4">
      <%= yield %>
  </div>

</body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
    <% @post.errors.full_messages.each do | message | %>
        <%= message%>
    <% end %>
<% end %>

<%= form_for @post, html:{class: "form-horizontal"} do |f| %>
    <div class="form-group"> 
        <div class="mb-3 row">
            <div class="col-6">
                <%= f.label :title, class: "form-label"%>
                <%= f.text_field :title, class: "form-control" %>
            </div>
        </div>
    </div>
    <div>
        <div class="mb-3 row">
            <div class="col-6">
                <%= f.label :description, class: "form-label"%>
                <%= f.text_area :description, class: "form-control" %>
            </div>
        </div>
    </div>
    <div>
        <div class="mb-3 row">
            <div class="col-6">
                <%= f.label :marktsegment, class: "form-label" %>
            </div>
        </div>
    </div>
    <div>
        <div class="mb-3 row">
            <div class="col-6">
                <%= f.radio_button :marktsegment, 'B2B' %> B2B
                <%= f.radio_button :marktsegment, 'B2C' %> B2C
                <%= f.radio_button :marktsegment, 'Andere' %> Andere
            </div>
        </div>
    </div>
    <div>
        <div class="mb-3 row">
            <div class="col-6">
                <%= f.label :help, class: "form-label"%>
                <%= f.text_area :help, class: "form-control" %>
            </div>
        </div>
    </div>
    <div>
        <div class="mb-3 row">
            <div class="col-6">
                <%= f.label :keywords, class: "form-label"%>
                <%= f.text_field :keywords, class: "form-control" %>
            </div>
        </div>
    </div>
    <div>
        <%= f.submit "Jetzt Pitchen", class: "btn btn-primary" %>
    </div>

<% end %>

app/views/posts/edit.html.erb
<h1> Pitch bearbeiten </h1>
<%= render partial: 'posts/form' %>

app/views/posts/index.html.erb
<h1>PitchWeb</h1>

<table class="table">
    <thead class="table-light">
        <tr>
        <th scope="col">Pitch Nummer:</th>
        <th scope="col">Pitch Titel</th>
        <th scope="col">Pitch lesen</th>
        <th scope="col">Pitch editieren</th>
        <th scope="col">Pitch löschen</th>
        </tr>
    </thead>
    <% @posts.each_with_index do | post, i | %>
    <tbody>
        <tr class="table-light">
        <th scope="row"><%= 1 + i %></th>
        <td><%= post.title %></td>
        <td><%= link_to 'Pitch ansehen', post_path(post), class: "btn btn-outline-primary"%></td>
        <td><%= link_to 'Pitch editieren', edit_post_path(post), class: "btn btn-outline-primary"%></td>
        <td><%= link_to 'Pitch löschen', post_path(post), method: 'DELETE', class: "btn btn-outline-primary"%></td>
        </tr>
    </tbody>

    <% end %>
</table>

app/views/posts/new.html.erb
<h1> Neuer Pitch </h1>
<%= render partial: 'posts/form' %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<ul class="list-group">
    <li class="list-group-item">
        <p class="fw-lighter">Beschreibung:</p>
        <p>
            <%= @post.description %>
        <p>
    </li>
    <li class="list-group-item">
        <p class="fw-lighter">Marktsegment:</p>
        <p>
            <%= @post.marktsegment %>
        <p>
    </li>
    <li class="list-group-item">
        <p class="fw-lighter">Benötigte Hilfe:</p>
        <p>
            <%= @post.help %>
        <p>
    </li>
    <li class="list-group-item mb-3">
        <p class="fw-lighter">Tags:</p>
        <p>
            <%= @post.keywords %>
        <p>
    </li>
</ul>
<%= link_to 'Pitch editieren', edit_post_path(@post), class: "btn btn-primary mb-5"%>


<h3> Kommentiere meinen Pitch </h3>
<div class="form-group">
    <%= form_for [@post, Comment.new] do |f| %>
        <div class="mb-3 row">
            <div class="col-6">
                <div>
                    <%= f.label :text, class: "form-label"%>
                    <%= f.text_area :text, class: "form-control"  %>
                </div>
            </div>
        </div>
        <div class="mb-3 row">
            <div class="col-6">
                <div>
                    <%= f.label :name, class: "form-label"%>
                    <%= f.text_field :name, class: "form-control"  %>
                </div>
            </div>
        </div>
        <div class="mb-3 row">
            <div class="col-6">
                <div>
                    <%= f.label :email, class: "form-label"%>
                    <%= f.email_field :email, class: "form-control" %>
                </div>
            </div>
        </div>
        <div class="mb-3 row">
            <div class="col-6">
                <div>
                    <%= f.submit "Kommentar erstellen", class:"btn btn-primary" %>
                </div>
            </div>
        </div>
</div>
<% end %>


<h3 class="mt-5">Kommentare</h3>
<ul class="list-group"> 
    <% @post.comments.order(created_at: :desc).each do | comment | %>
        <li class="list-group-item mb-5">
            <%= comment.text %>
            <p>Eine E-mail schreiben an: <%= link_to comment.name, "mailto:#{comment.email}" %></p>
            <p><%= link_to 'Kommentar Löschen', post_comment_path(@post, comment), method: 'DELETE', class: "btn btn-outline-primary" %><p>
        </li>
<% end %>